# Generated by Django 5.1.4 on 2024-12-07 04:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(default='CVE-0000-00000', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='ID уязвимости должен быть в формате CVE-YYYY-XXXXX', regex='^CVE-\\d{4}-\\d{5}$')], verbose_name='ID уязвимости')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('publication_date', models.DateField(verbose_name='Дата публикации')),
                ('source_link', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на источник')),
                ('exploits_poc', models.TextField(verbose_name='Эксплойты и PoC')),
            ],
            options={
                'verbose_name': 'Уязвимость',
                'verbose_name_plural': 'Уязвимости',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Запрос')),
                ('search_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vulnerabilities', models.ManyToManyField(blank=True, to='parsingVulnerabilities.vulnerability', verbose_name='Уязвимости')),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'Истории поиска',
            },
        ),
    ]
