# Generated by Django 5.1.4 on 2024-12-07 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parsingVulnerabilities', '0002_exploit_remove_vulnerability_exploits_poc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_or_domain', models.CharField(max_length=255, verbose_name='IP или домен')),
                ('status', models.CharField(choices=[('vulnerable', 'Уязвим'), ('not_vulnerable', 'Не уязвим'), ('error', 'Ошибка'), ('other', 'Другое')], max_length=50, verbose_name='Статус')),
                ('applied_exploits', models.TextField(blank=True, verbose_name='Примененные эксплойты и РоС')),
                ('vulnerable_services_or_apps', models.TextField(blank=True, verbose_name='Уязвимые сервисы или приложения')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Запрос')),
                ('search_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vulnerabilities', models.ManyToManyField(blank=True, to='parsingVulnerabilities.vulnerability', verbose_name='Уязвимости')),
            ],
            options={
                'verbose_name': 'История сканирования',
                'verbose_name_plural': 'Истории сканирования',
            },
        ),
    ]
