# Generated by Django 5.1.4 on 2024-12-08 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkQueries', '0003_scanhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='ip_or_domain',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Введите корректный IP-адрес или домен', regex='^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$|^(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}$')], verbose_name='IP или домен'),
        ),
    ]
