# Generated by Django 5.1.4 on 2024-12-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkQueries', '0005_remove_scanhistory_vulnerabilities'),
        ('parsingVulnerabilities', '0006_alter_exploit_exploit_id_alter_exploit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='vulnerabilities',
            field=models.ManyToManyField(blank=True, to='parsingVulnerabilities.vulnerability', verbose_name='Уязвимости'),
        ),
    ]
