# Generated by Django 5.1.4 on 2024-12-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkQueries', '0006_scanhistory_vulnerabilities'),
        ('parsingVulnerabilities', '0006_alter_exploit_exploit_id_alter_exploit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanhistory',
            name='vulnerabilities',
        ),
        migrations.AddField(
            model_name='query',
            name='vulnerabilities',
            field=models.ManyToManyField(blank=True, to='parsingVulnerabilities.vulnerability', verbose_name='Уязвимости'),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('secured', 'Защищен'), ('vulnerable', 'Уязвим'), ('other', 'Другое')], max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkQueries.query', verbose_name='Запрос'),
        ),
    ]
